### PR TITLE
Galvan dvc experiment

### PR DESCRIPTION
**Pull request by ggjx22**
hello @ellacharmed please review this pr before this feature branch is merged into main. thanks!

### CODE REVIEW

**Comment by ellacharmed** [comment]
commit [76220b4](https://github.com/ai-practitioners/time-series-forecasting/pull/6/commits/76220b4f2760727c7eaa17de1e0e8920139f6536) is preventing me to do a `dvc pull`

**Comment by ellacharmed** [comment]
I also propose that we remove the datetime stamp on the dump filename so we can just do versioning on the dumped file.

**Comment by ggjx22** [comment]
> commit [76220b4](https://github.com/ai-practitioners/time-series-forecasting/pull/6/commits/76220b4f2760727c7eaa17de1e0e8920139f6536) is preventing me to do a `dvc pull`

this is fixed by removing `*.sql` from .dvcignore. thanks @ellacharmed !

**Comment by ggjx22** [comment]
> I also propose that we remove the datetime stamp on the dump filename so we can just do versioning on the dumped file.
> 
> One thing to note, when the dumped file is recreated/refresh for whatever reason, the `data_loader.py` is still loading from database endpoint that might be different from the contents of DBDump.sql file.
> 
> Also need to add a step in documentation that Workbench need to be refreshed with database from new DBDump.sql

Can I know why do we need to recreate the dump.sql file in the first place? My understanding is that the dump.sql allows us to have the same rows x columns across our local database. From here on, the changes will be on the scripts to query whatever data that we want.

We could have an additional statement at the top of the dump.sql (see below). So that whenever the dump file got recreated, it deletes the previous time_series database and creates a new one? Does it solve the issue with `data_loader.py` pointing to the wrong endpoint?
`DROP DATABASE IF EXISTS 'time_series';`

Agree on the proposal to have better naming for the dump filename, if we are doing versioning on it.

**Comment by ellacharmed** [comment]
> Can I know why do we need to recreate the dump.sql file in the first place? 

The `train` table is short by 10k rows for some reason. That's why I didn't see the 3mil rows in total. If we want to improve sql performance, I forsee more tweaks as none of the tables are indexed at the moment. I might have done indexing for 1 or 2 tables while crafting the join query, but cannot be sure if the dump file was created before or after the indexing step took place.

> We could have an additional statement at the top of the dump.sql (see below). So that whenever the dump file got recreated, it deletes the previous time_series database and creates a new one? Does it solve the issue with `data_loader.py` pointing to the wrong endpoint? `DROP DATABASE IF EXISTS 'time_series';`

Oh, I thought it already had this. And there's only the check for if table exists, no check for database. So, yes, can edit the file to include.

> Agree on the proposal to have better naming for the dump filename, if we are doing versioning on it.

👍🏽

**Pull request merged**
